# Generated by Django 2.1.2 on 2018-10-26 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import pbs.document.fields
import pbs.document.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('custom_tag', models.CharField(blank=True, max_length=64, verbose_name='Custom Descriptor')),
                ('document', pbs.document.fields.ContentTypeRestrictedFileField(help_text='Acceptable file types: pdf, tiff, jpg, gif, png, zip', max_length=200, upload_to=pbs.document.models.content_file_name)),
                ('document_created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date Document Created')),
                ('document_archived', models.BooleanField(default=False, verbose_name='Archived Document')),
            ],
            options={
                'ordering': ['tag', 'document'],
                'permissions': (('archive_document', 'Can archive documents'),),
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'Document Categories',
                'verbose_name': 'Document Category',
            },
        ),
        migrations.CreateModel(
            name='DocumentTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Document Tag')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='document.DocumentCategory')),
            ],
            options={
                'ordering': ['name'],
                'base_manager_name': 'objects',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='document.DocumentCategory'),
        ),
        migrations.AddField(
            model_name='document',
            name='creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_document_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='modifier',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_document_modified', to=settings.AUTH_USER_MODEL),
        ),
    ]
