# Generated by Django 2.1.2 on 2018-10-26 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('document', '0001_initial'),
        ('prescription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='prescription',
            field=models.ForeignKey(help_text='Prescription that this document belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, to='prescription.Prescription'),
        ),
        migrations.AddField(
            model_name='document',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='document.DocumentTag', verbose_name='Descriptor'),
        ),
    ]
