# Generated by Django 2.1.2 on 2018-12-06 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0003_auto_20181129_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundingallocation',
            name='allocation',
            field=models.PositiveSmallIntegerField(choices=[(72, '72 - Prescribed fire'), (42, '42 - Native forest'), (43, '43 - Plantations'), (7204, '72-04 - Recoupable projects')], help_text='Program funding code which is assigned to the burn', verbose_name='Program'),
        ),
    ]
