# Generated by Django 2.1.2 on 2019-01-04 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0004_auto_20181206_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionalobjective',
            name='impact',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Region'), (2, 'Fire Management Area')], default=1, help_text='Area of application for objective', verbose_name='Scale of Application'),
        ),
        migrations.AlterField(
            model_name='regionalobjective',
            name='objectives',
            field=models.TextField(verbose_name='Burn objectives'),
        ),
    ]
