# Generated by Django 2.1.2 on 2018-10-26 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prescription', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('relevant', models.BooleanField(default=True, help_text='Include in Action List', verbose_name='Action Relevant?')),
                ('pre_burn', models.BooleanField(default=False)),
                ('details', models.TextField(blank=True, verbose_name='Action Details')),
                ('pre_burn_resolved', models.CharField(blank=True, choices=[('No', 'No'), ('Yes', 'Yes, as planned'), ('Explanation', 'Yes, with explanation')], default='No', max_length=200, verbose_name='Issue Resolved')),
                ('pre_burn_completer', models.TextField(blank=True, null=True, verbose_name='Actioned By Whom')),
                ('pre_burn_completed', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Date Actioned')),
                ('pre_burn_explanation', models.TextField(blank=True, verbose_name='Explanation')),
                ('day_of_burn', models.BooleanField(default=False)),
                ('day_of_burn_responsible', models.CharField(choices=[('IC', 'IC'), ('OPS', 'OPS')], default='IC', max_length=200, verbose_name='Responsible')),
                ('day_of_burn_completer', models.TextField(blank=True, null=True, verbose_name='Actioned By Whom')),
                ('day_of_burn_completed', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Date Actioned')),
                ('day_of_burn_include', models.BooleanField(default=False, verbose_name='Include in Briefing?')),
                ('day_of_burn_situation', models.BooleanField(default=False, verbose_name='S')),
                ('day_of_burn_mission', models.BooleanField(default=False, verbose_name='M')),
                ('day_of_burn_execution', models.BooleanField(default=False, verbose_name='E')),
                ('day_of_burn_administration', models.BooleanField(default=False, verbose_name='A')),
                ('day_of_burn_command', models.BooleanField(default=False, verbose_name='C')),
                ('day_of_burn_safety', models.BooleanField(default=False, verbose_name='S')),
                ('post_burn', models.BooleanField(default=False)),
                ('post_burn_completer', models.TextField(blank=True, null=True, verbose_name='Actioned By Whom')),
                ('post_burn_completed', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Date Actioned')),
                ('context_statement', models.BooleanField(default=False, verbose_name='Relevant to Context Statement?')),
                ('index', models.PositiveSmallIntegerField(default=1, editable=False, help_text='Index of this action in the set of actions for this risk', verbose_name='Index of this action')),
                ('total', models.PositiveSmallIntegerField(default=1, editable=False, verbose_name='Total number of actions for this risk')),
                ('creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_action_created', to=settings.AUTH_USER_MODEL)),
                ('modifier', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_action_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['risk__category', '-relevant', 'risk__name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Complexity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('factor', models.CharField(max_length=64)),
                ('sub_factor', models.CharField(max_length=64, verbose_name='Sub-factor')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('rating', models.PositiveSmallIntegerField(choices=[(0, 'Unrated'), (2, 'Low'), (3, 'Medium'), (4, 'High')], default=0, verbose_name='Complexity Rating')),
                ('rationale', models.TextField(blank=True, verbose_name='Complexity Rationale')),
                ('creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_complexity_created', to=settings.AUTH_USER_MODEL)),
                ('modifier', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_complexity_modified', to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(blank=True, help_text='Prescription this Complexity belongs to.', null=True, on_delete=django.db.models.deletion.PROTECT, to='prescription.Prescription')),
            ],
            options={
                'ordering': ['order'],
                'verbose_name_plural': 'Complexity Analysis Items',
                'verbose_name': 'Complexity Analysis Item',
            },
        ),
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('statement', models.TextField(blank=True, verbose_name='Context Statement')),
                ('creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_context_created', to=settings.AUTH_USER_MODEL)),
                ('modifier', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_context_modified', to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(help_text='Prescription this issue belongs to.', on_delete=django.db.models.deletion.PROTECT, to='prescription.Prescription')),
            ],
            options={
                'ordering': ['pk'],
                'verbose_name_plural': 'Context Statement Items',
                'verbose_name': 'Context Statement Item',
            },
        ),
        migrations.CreateModel(
            name='ContextRelevantAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('considered', models.BooleanField(default=False, help_text='Has this action been considered as part of writing the context statement?', verbose_name='Considered?')),
                ('action', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='context_considered', to='risk.Action', verbose_name='Action relevant for context statement')),
                ('creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_contextrelevantaction_created', to=settings.AUTH_USER_MODEL)),
                ('modifier', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_contextrelevantaction_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contingency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(help_text='Contingency Details', verbose_name='Contingency')),
                ('trigger', models.TextField(help_text='Trigger')),
                ('actions_migrated', models.BooleanField(default=True)),
                ('action', models.TextField(blank=True, help_text='List of Actions', null=True)),
                ('notifications_migrated', models.BooleanField(default=True)),
                ('notify_name', models.TextField(blank=True, null=True, verbose_name='Notify (Name)')),
                ('location', models.TextField(blank=True, null=True)),
                ('organisation', models.TextField(blank=True, null=True)),
                ('contact_number', models.TextField(blank=True, null=True)),
                ('creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_contingency_created', to=settings.AUTH_USER_MODEL)),
                ('modifier', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_contingency_modified', to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(help_text='Prescription this objective belongs to.', on_delete=django.db.models.deletion.PROTECT, to='prescription.Prescription')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name_plural': 'Contingencies',
                'verbose_name': 'Contingency',
            },
        ),
        migrations.CreateModel(
            name='ContingencyAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('action', models.TextField(blank=True, null=True)),
                ('contingency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='risk.Contingency')),
                ('creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_contingencyaction_created', to=settings.AUTH_USER_MODEL)),
                ('modifier', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_contingencyaction_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContingencyNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Notify (Name)')),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('organisation', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=100, null=True)),
                ('contingency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='risk.Contingency')),
                ('creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_contingencynotification_created', to=settings.AUTH_USER_MODEL)),
                ('modifier', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_contingencynotification_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, verbose_name='Risk Description')),
                ('draft_consequence', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], default=6, verbose_name='Consequence')),
                ('draft_likelihood', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Rare'), (2, 'Unlikely'), (3, 'Possible'), (4, 'Likely'), (5, 'Almost Certain')], default=5, verbose_name='Likelihood')),
                ('draft_risk_level', models.PositiveSmallIntegerField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Medium'), (4, 'High'), (5, 'Very High')], default=5, editable=False, verbose_name='Draft ePFP Risk Level')),
                ('alarp', models.BooleanField(default=False, verbose_name='As Low As Reasonably Practicable?')),
                ('final_consequence', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], default=3, verbose_name='Revised Consequence')),
                ('final_likelihood', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Rare'), (2, 'Unlikely'), (3, 'Possible'), (4, 'Likely'), (5, 'Almost Certain')], default=5, verbose_name='Revised Likelihood')),
                ('final_risk_level', models.PositiveSmallIntegerField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Medium'), (4, 'High'), (5, 'Very High')], default=5, editable=False, verbose_name='Final ePFP Risk Level')),
                ('creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_register_created', to=settings.AUTH_USER_MODEL)),
                ('modifier', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_register_modified', to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(help_text='Prescription this risk register item belongs to.', on_delete=django.db.models.deletion.PROTECT, to='prescription.Prescription')),
            ],
            options={
                'ordering': ('pk',),
                'verbose_name_plural': 'Risk Register Items',
                'verbose_name': 'Risk Register Item',
            },
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Potential Source of Risk')),
                ('risk', models.PositiveSmallIntegerField(choices=[(1, 'Unassessed'), (2, 'Uncertainty'), (3, 'Assumption'), (4, 'Not Applicable')], default=1)),
                ('custom', models.BooleanField(default=True, help_text='Is this a non standard source of risk?', verbose_name='Non standard source of risk')),
            ],
            options={
                'ordering': ['category', 'name'],
                'verbose_name': 'Potential Sources of Risk',
            },
        ),
        migrations.CreateModel(
            name='RiskCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Potential Source of Risk Category')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'Potential Source of Risk Categories',
                'verbose_name': 'Potential Source of Risk Category',
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('complete', models.BooleanField(default=False, verbose_name='Dealt With?')),
                ('creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_treatment_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='TreatmentLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='treatment',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='risk.TreatmentLocation'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='modifier',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_treatment_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='treatment',
            name='register',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='risk.Register'),
        ),
        migrations.AddField(
            model_name='risk',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='risk.RiskCategory'),
        ),
        migrations.AddField(
            model_name='risk',
            name='creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_risk_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='risk',
            name='modifier',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_risk_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='risk',
            name='prescription',
            field=models.ForeignKey(blank=True, help_text='Prescription this issue belongs to.', null=True, on_delete=django.db.models.deletion.PROTECT, to='prescription.Prescription'),
        ),
        migrations.AddField(
            model_name='action',
            name='risk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='risk.Risk', verbose_name='Potential Source of Risk'),
        ),
    ]
