# Generated by Django 2.1.2 on 2018-12-06 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='context',
            name='prescription',
            field=models.OneToOneField(help_text='Prescription this issue belongs to.', on_delete=django.db.models.deletion.PROTECT, to='prescription.Prescription'),
        ),
    ]
